from __future__ import annotations

from typing import Protocol


class CustomerRepository(Protocol):
    def list_customers(self) -> list: ...

    def get_customer(self, customer_id: int): ...

    def get_customer_by_phone(self, telefone: str): ...

    def create_customer(self, nome: str, telefone: str) -> None: ...

    def upsert_customer(self, nome: str, telefone: str) -> int: ...

    def update_customer(self, customer_id: int, nome: str, telefone: str) -> None: ...

    def delete_customer(self, customer_id: int) -> None: ...
